Experiment 1: TensorFlow Installation & Version Check

TENSORLOW INSTALLATION

In [2]:
pip install tensorflow


IMPORTING TENSORFLOW

In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


Experiment 2: Creating and Printing Tensors

In [8]:
#SCALAR TENSOR
a=tf.constant(5)
print(a)

#VECTOR TENSOR
v=tf.constant([1,2,3,4,])
print(v)

#MATRIX TENSOR
m=tf.constant([[1,2],[3,4]])
print(m)

t3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


Experiment 3: Basic Tensor Operations

In [13]:
# --------SCALAR---------

a=tf.constant(10)
b=tf.constant(20)

# ADDITION
print(a+b)

#SUBTRACTION
print(a-b)

#MULTIPLICATION
print(a*b)

#DIVISION
print(a/b)

tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(-10, shape=(), dtype=int32)
tf.Tensor(200, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)


In [14]:
# --------VECTOR---------

a=tf.constant([10,20,30])
b=tf.constant([40,50,60])

# ADDITION
print(a+b)

#SUBTRACTION
print(a-b)

#MULTIPLICATION
print(a*b)

#DIVISION
print(a/b)

tf.Tensor([50 70 90], shape=(3,), dtype=int32)
tf.Tensor([-30 -30 -30], shape=(3,), dtype=int32)
tf.Tensor([ 400 1000 1800], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [16]:
# --------2D-MATRIX---------

a=tf.constant([[10,20],[30,40]])
b=tf.constant([[50,60],[70,80]])

# ADDITION
print(a+b)

#SUBTRACTION
print(a-b)

#MULTIPLICATION
print(a*b)

#DIVISION
print(a/b)

tf.Tensor(
[[ 60  80]
 [100 120]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-40 -40]
 [-40 -40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 500 1200]
 [2100 3200]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


Experiment 4: Data Types and Shape of Tensors

In [17]:
# -------Scalar---------
a = tf.constant(10)

print("Value:", a)
print("Data Type:", a.dtype)
print("Shape:", a.shape)
print("Number of Dimensions:", a.ndim)
print("\n")


# -------Vector---------
b = tf.constant([1, 2, 3, 4])

print("Value:\n", b)
print("Data Type:", b.dtype)
print("Shape:", b.shape)
print("Number of Dimensions:", b.ndim)
print("\n")


# ----------2D Matrix------------
c = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

print("Value:\n", c)
print("Data Type:", c.dtype)
print("Shape:", c.shape)
print("Number of Dimensions:", c.ndim)

Value: tf.Tensor(10, shape=(), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: ()
Number of Dimensions: 0


Value:
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: (4,)
Number of Dimensions: 1


Value:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: 2


Experiment 5: Converting NumPy Arrays to Tensors

In [19]:
import numpy as np

numpy_array = np.array([[10, 20, 30],
                        [40, 50, 60]])

tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:\n", numpy_array)
print("\nTensorFlow Tensor:\n", tensor)


NumPy Array:
 [[10 20 30]
 [40 50 60]]

TensorFlow Tensor:
 tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int64)
